services:
  rfpc-web:
    build:
      context: .
      dockerfile: dockerfile
    image: rfpc-web:latest
    container_name: rfpc-web
    restart: always
    ports:
      - "10022:80"
    environment:
      TZ: America/Tegucigalpa
    networks:
      - operacion-net

networks:
  operacion-net:
    external: true
