services:
  rfpc-web2:
    build:
      context: .
      dockerfile: dockerfile
    image: rfpc-web2:latest
    container_name: rfpc-web2
    restart: always
    ports:
      - "10022:80"
    environment:
      TZ: America/Tegucigalpa
    networks:
      - operacion-net

networks:
  operacion-net:
    external: true
